### ISSUE TITLE
Too big

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/ubuntu-core-kiosk#8]
Probably because of the inclusion of swaybg this is bigger than mir-kiosk:
```
$ ls -lh /var/lib/snapd/snaps/ubuntu-core-kiosk_*.snap /var/lib/snapd/snaps/mir-kiosk_*.snap
-rw------- 1 root root 47M Mar 22 11:33 /var/lib/snapd/snaps/mir-kiosk_6592.snap
-rw------- 1 root root 47M Mar 25 12:27 /var/lib/snapd/snaps/mir-kiosk_6615.snap
-rw------- 1 root root 53M May 17 16:53 /var/lib/snapd/snaps/ubuntu-core-kiosk_25.snap
-rw------- 1 root root 53M May 18 08:29 /var/lib/snapd/snaps/ubuntu-core-kiosk_29.snap
```

**Comment by wmww** [comment]
It looks to me like it's mostly LLVM and graphics drivers (same as mir-kiosk). `libicudata.so.66.1` is quite big and __not__ present in mir-kiosk. Is that being included by swaybg?

**Comment by AlanGriffiths** [comment]
Well, not looked at specific files, but dropping swaybg locally saves 12M. Maybe that's not the best way to do a background.

**Comment by wmww** [comment]
Perhaps color should be a startup option. Then we could default to dark gray (as I want), and keep mir-kiosk override that with black for backwards compat. ubuntu-core-kiosk could override that with whatever it wants without an out-of-process background.

**Comment by AlanGriffiths** [comment]
> Perhaps color should be a startup option. Then we could default to dark gray (as I want), and keep mir-kiosk override that with black for backwards compat. ubuntu-core-kiosk could override that with whatever it wants without an out-of-process background.

It would probably be simpler to adapt the internal background code from miral-shell or egmde. (Eventually, the "custom compositing" feature we want to re-introduce should make this easy.)

**Comment by AlanGriffiths** [comment]
FWIW using the mesa-core20 content snap with mir-kiosk drops the size to:

-rw-r--r-- 1 alan alan 6.4M May 20 11:15 mir-kiosk_2.3.3-snap120_amd64.snap
